//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Scripts/JetControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @JetControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @JetControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""JetControls"",
    ""maps"": [
        {
            ""name"": ""Jet"",
            ""id"": ""33062b98-bd48-4adb-98a5-f638f771a4b1"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""bf5fabbf-c1d7-4c32-8e96-09a25fb935c1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5350b2f9-217b-47ce-a617-cc38f4dec2c3"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Jet
        m_Jet = asset.FindActionMap("Jet", throwIfNotFound: true);
        m_Jet_Movement = m_Jet.FindAction("Movement", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Jet
    private readonly InputActionMap m_Jet;
    private IJetActions m_JetActionsCallbackInterface;
    private readonly InputAction m_Jet_Movement;
    public struct JetActions
    {
        private @JetControls m_Wrapper;
        public JetActions(@JetControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Jet_Movement;
        public InputActionMap Get() { return m_Wrapper.m_Jet; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(JetActions set) { return set.Get(); }
        public void SetCallbacks(IJetActions instance)
        {
            if (m_Wrapper.m_JetActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_JetActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_JetActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_JetActionsCallbackInterface.OnMovement;
            }
            m_Wrapper.m_JetActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
            }
        }
    }
    public JetActions @Jet => new JetActions(this);
    public interface IJetActions
    {
        void OnMovement(InputAction.CallbackContext context);
    }
}
